# Data Preprocessing

## Importación de librerias

In [1]:
#Trabajar con arrays
import numpy as np

#Graficas
import matplotlib.pyplot as plt

#Importar datasets, etc...
import pandas as pd

## Importación de dataset

In [2]:
dataset = pd.read_csv('Data.csv')

X = dataset.iloc[:,:-1].values
Y = dataset.iloc[:,-1].values

#Ver con print(X) y print(Y)

## Manejando los datos perdidos  

In [3]:
#Herramientas de Data Preprocessing 
#Nota: los valores en esta sección cambian depende del dataset 

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:,1:3])
X[:,1:3] = imputer.transform(X[:,1:3])
#ver con print(X)

## Codificando datos categóricos 

In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

#Primero los 3 paises de este ejemplo

ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [5]:
#Ver resultados
#print(X) 

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


## Codificando la variable dependiente

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)

In [8]:
#Ver resultados
#print(Y)

[0 1 0 0 1 1 0 1 0 1]


## Separando el dataset en entrenamiento y prueba

In [9]:
from sklearn.model_selection import train_test_split

#Nos regresara estas 4 variables ya llenas con los datos del train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2, random_state = 1)


In [10]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [11]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [12]:
print(Y_train)

[0 1 0 0 1 1 0 1]


In [13]:
print(Y_test)

[0 1]


## Función de escala

In [17]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

#Aplicará Feature scaling fit a las columnas edad y salario 
X_train[:,3:] = sc.fit_transform(X_train[:,3:])

#Aplicará Feature scaling solo el método transform 
X_test[:,3:] = sc.transform(X_test[:,3:])

In [18]:
print(X_train)

[[0.0 0.0 1.0 -0.1915918438457856 -1.0781259408412427]
 [0.0 1.0 0.0 -0.014117293757057902 -0.07013167641635401]
 [1.0 0.0 0.0 0.5667085065333239 0.6335624327104546]
 [0.0 0.0 1.0 -0.3045301939022488 -0.30786617274297895]
 [0.0 0.0 1.0 -1.901801144700799 -1.4204636155515822]
 [1.0 0.0 0.0 1.1475343068237056 1.2326533634535488]
 [0.0 1.0 0.0 1.4379472069688966 1.5749910381638883]
 [1.0 0.0 0.0 -0.7401495441200352 -0.5646194287757336]]


In [19]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


Finalizando el template para el data preprocessing en un futuro solo cambiar variables necesarias.